const indonesianAbbreviationMap = {
  drpd: "daripada",
  akr: "akronim",
  dp: "daripada",
  msl: "misalnya",
  tp: "tapi",
  kpada: "kepada",
  krn: "karena",
  org: "orang",
  dll: "dan lain-lain",
  utk: "untuk",
  dlm: "dalam",
  dr: "dari",
  dsb: "dan sebagainya",
  dst: "dan seterusnya",
  ki: "kiasan",
  kp: "kependekan",
  spt: "seperti",
  thd: "terhadap",
  tt: "istilah ini tentang",
  ttg: "istilah ini tentang",
  dr: "dari",
  pd: "pada",
  pb: "peribahasa",
  yg: "yang",
  sing: "singkatan",
  sbg: "sebagai",
  dng: "dengan",
  dgn: "dengan",
  dg: "dengan",
};

const englishAbbreviationMap = {
  ETA: "estimated time of arrival",
  LMK: "let me know",
  BRB: "be right back",
  DOB: "date of birth",
};

export { englishAbbreviationMap, indonesianAbbreviationMap };
